# Python Project Day-19

Q63). By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155]. Hints: Use list's remove method to delete a value.

In [1]:
ls =[12 ,24 ,35 ,24 ,88 ,120 ,155]
a=24

for i,v in enumerate(ls):
    
    if v==a:
        del ls[i]

In [2]:
ls

[12, 35, 88, 120, 155]

In [3]:
ls=[12,24,35,24,88,120,155]
ls=[x for x in ls if x!=24]
print(ls)

[12, 35, 88, 120, 155]


Q64). With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists. Hints: Use set() and "&=" to do set intersection operation.

In [4]:
set1=set([1,3,6,78,35,55])
set2=set([12,24,35,24,88,120,155])
set1 &= set2
ls=list(set1)
print(ls)

[35]


Q65). With a given list [12, 24, 35, 24, 88, 120, 155, 88, 120, 155], write a program to print this list after removing all duplicate values with original order reserved. Hints: Use set() to store a number of values without duplicate.

In [5]:
ls=[12,24,35,24,88,120,155,88,120,155]
ls1=ls.reverse()
for i in ls:
    if ls.count(i)>1:
        ls.remove(i)
print(ls)

[155, 120, 88, 35, 24, 12]
